# Generated by Django 4.0.6 on 2022-07-22 11:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='package',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air fares', 'Air fares'), ('4 Nights Hotel Accomodation', '4 Nights Hotel Accomodation'), ('Entrance Fees', 'Entrance Fees'), ('Tour Guide', 'Tour Guide')], max_length=200, null=True),
        ),
    ]
