# Generated by Django 4.0.6 on 2022-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapps', '0004_order_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack')], default='PayStack', max_length=20),
        ),
    ]
