# Generated by Django 4.0.6 on 2022-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapps', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayStack', 'PayStack')], default='PayStack', max_length=20),
        ),
    ]
